name: smartpay
description: "An apex mobile app test."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar_v2: ^5.3.0
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.26
  mvc_pattern: ^8.12.0
  http: ^1.2.1
  fluttertoast: ^8.2.5
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
